name: Android Lint

on:
  workflow_call:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-gradle
      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Run Android Lint
        run: ./gradlew lint --parallel --stacktrace --no-configuration-cache --no-daemon

      - name: Upload Lint HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-html
          path: '**/build/reports/lint-results*.html'

      # - name: Upload SARIF to GitHub Code Scanning
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@v4
      #   with:
      #     sarif_file: '**/build/reports/lint-results.sarif'
