name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
  API_TOKEN: ${{ secrets.API_TOKEN }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/init-gradle

      - name: Create google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Build project $gradleFlags
        run: ./gradlew assembleDebug

      - name: Generate build time report
        uses: ./.github/actions/build-time-report
        with:
          file: app/build/reports/buildTimeTracker/build.csv
          output-file: buildTime.csv


  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/init-gradle

      - name: Create google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Run unit tests (Debug only)
        run: ./gradlew testDebugUnitTest $gradleFlags


  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/init-gradle

      - name: Create google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Upload Lint HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-html
          path: |
            **/build/reports/lint-results*.html

      - name: Upload SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: |
            lint/build/reports/lint-results.sarif


  run-detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/init-gradle

      - name: Run Detekt
        run: ./gradlew detekt $gradleFlags

      - name: Generate Markdown report
        run: cat build/reports/detekt/detekt.md > $GITHUB_STEP_SUMMARY

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: detekt.html
          path: build/reports/detekt/detekt.html


  run-ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/init-gradle

      - name: Run KtLint
        run: ./gradlew --continue ktlintCheck $gradleFlags

      - name: Publish KtLint summary
        if: always()
        run: |
          echo '### KtLint Report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          find . -type f -path "*/build/reports/ktlint/*.txt" -exec cat {} \; >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Install sarif-tools
        if: always()
        run: npm install -g @microsoft/sarif-tools

      - name: Merge ktlint SARIF reports
        if: always()
        run: |
          mkdir -p sarif
          sarif merge \
            $(find . -type f -path "*/build/reports/ktlint/*/*.sarif") \
            --output sarif/ktlint.sarif

      - name: Upload merged ktlint SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: sarif/ktlint.sarif
          category: ktlint

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-html
          path: '**/build/reports/ktlint/*/*.html'


  check-module-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/init-gradle

      - name: Check Graph
        run: ./gradlew :app:assertModuleGraph $gradleFlags

      - name: Generate graph
        run: ./gradlew :app:generateModulesGraphvizText -Pmodules.graph.output.gv=all_modules $gradleFlags

      - name: Generate Markdown report
        run: |
          set -e
          echo '```' > $GITHUB_STEP_SUMMARY
          cat all_modules >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Draw graph
        uses: ./.github/actions/draw-graph

        with:
          input-file: all_modules
          output-file: all_modules.png

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: all_modules.png
          path: all_modules.png
