name: Build App release

on:
  workflow_dispatch:
  push:
    branches:
      - 'test/**'
    paths-ignore:
      - '**.md'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
  ANDROID_SDK_ROOT: /usr/lib/android-sdk
  API_TOKEN: ${{ secrets.API_TOKEN }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/android-setup
      - name: Build unsigned AAB
        run: ./gradlew :app:bundleRelease $gradleFlags -x validateSigningRelease
      - name: Generate build time report
        uses: ./.github/actions/build-time-report
        with:
          file: app/build/reports/buildTimeTracker/build.csv
          output-file: buildTime.csv
      - name: Upload unsigned AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-unsigned
          path: app/build/outputs/bundle/release/app-release.aab
      - name: Upload time report
        uses: actions/upload-artifact@v4
        with:
          name: buildTime.csv
          path: buildTime.csv

  sign-app:
    runs-on: ubuntu-latest
    needs: build-app
    env:
      JKS_KS_PASS: ${{ secrets.JKS_KS_PASS }}
      JKS_KEY_PASS: ${{ secrets.JKS_KEY_PASS }}
      JKS_ALIAS: ${{ secrets.JKS_ALIAS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/download-artifact@v4
        with:
          name: app-unsigned

      - name: Create google-services.json
        uses: ./.github/actions/create-google-services

      - name: Decode keystore
        run: echo ${{ secrets.JKS_KS }} | base64 -d > release.jks

      - name: Sign bundle via Gradle
        run: |
          ./gradlew :app:bundleRelease \
            -Pandroid.injected.signing.store.file=release.jks \
            -Pandroid.injected.signing.store.password=$JKS_KS_PASS \
            -Pandroid.injected.signing.key.alias=$JKS_ALIAS \
            -Pandroid.injected.signing.key.password=$JKS_KEY_PASS

      - name: Upload signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-signed
          path: app/build/outputs/bundle/release/app-release.aab

  publish-google-play:
    runs-on: ubuntu-latest
    needs: sign-app
    if: startsWith(github.ref, 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: app-signed

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ secrets.PLAY_PACKAGE_NAME }}
          releaseFiles: app-release.aab
          track: internal
          status: completed
