name: Check Module Graph
on:
  workflow_call:

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon

jobs:
  check-module-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-gradle
      - name: Check Graph
        run: ./gradlew :app:assertModuleGraph ${{ env.gradleFlags }}
      - name: Generate graph
        run: ./gradlew :app:generateModulesGraphvizText -Pmodules.graph.output.gv=all_modules ${{ env.gradleFlags }}
      - name: Generate Markdown report
        run: |
          echo '```' > $GITHUB_STEP_SUMMARY
          cat all_modules >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - uses: ./.github/actions/draw-graph
        with:
          input-file: all_modules
          output-file: all_modules.png
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: all_modules.png
          path: all_modules.png
