name: Run Detekt
on:
  workflow_call:

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon

jobs:
  run-detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-gradle
      - name: Run Detekt
        run: ./gradlew detekt ${{ env.gradleFlags }} --continue
        continue-on-error: true
      - name: Generate Markdown report
        if: always()
        run: cat build/reports/detekt/detekt.md > $GITHUB_STEP_SUMMARY
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: build/reports/detekt/detekt.sarif
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt.html
          path: build/reports/detekt/detekt.html
      - name: Fail if Detekt found issues
        if: always()
        run: |
          if grep -q "<error" build/reports/detekt/detekt.xml; then
            echo "Detekt found issues!"
            exit 1
          else
            echo "No Detekt issues."
          fi
